### ISSUE TITLE
Headers of Grafana requests aren't forwarded to the HTTP request  

### ISSUE THREAD

**Issue by hgiasac** [wildmountainfarms/wild-graphql-datasource#7]
Headers of Grafana requests which include Cookie and OAuth identity aren't forwarded to HTTP requests of the data source.

**Comment by retrodaredevil** [comment]
[v1.3.0](https://github.com/wildmountainfarms/wild-graphql-datasource/releases/tag/v1.3.0) has this change. I just submitted a release, so my guess is that it'll be a few business days until 1.3.0 has been approved by Grafana.

As a note, anyone looking at this in the future should consider looking at the discussion here: #8, which has more technical details about the change.

**Comment by retrodaredevil** [comment]
1.3.0 had 1 vulnerability that prevented it from being released by Grafana. I will be submitting 1.3.1 today and hopefully that passes all of their checks.
