### ISSUE TITLE
Cannot pass [string!] variable type.

### ISSUE THREAD

**Issue by xav-ie** [wildmountainfarms/wild-graphql-datasource#9]
I was trying to use `[string!]` (string array) graphql type in the variables section like this:
```graphql
query plsWork($scriptNames: [string!]!) {
  viewer {
    scripts(filter: $scriptNames) {
      invocationCount
    }
  }
}
```
Here is my variables;
```json
{
 "scriptNames": ["some-script"]
}
```

Here is the error that is returned:
```
{
  "data": null,
  "errors": [
    {
      "message": "error parsing args for \"scripts\": filter: scriptName: not a list",
      "path": null,
      "extensions": {
        "timestamp": "2024-10-25T21:10:29.519268191Z"
      }
    }
  ]
}
```

^^ I had to edit the error a little bit, but the idea is that it is not a list. For some reason, the list in the actual graphql request is sent something like this:
```jsonc
// ...
"scriptName": {
 "0": "some-script"
}
// ...
```

When I copy the request as curl, edit the request to actually pass an array, it works! I think that this is a problem with this plugin because all the types are correct, I get no editor errors, and the request is transformed in a way I did not expect. I am not sure why this happens.

**Comment by retrodaredevil** [comment]
Yeah. Thanks for reporting this. I found the error and will get it fixed in 1.3.1
